Nyoba

diff --git a/AnyKernel/META-INF/com/google/android/update-binary b/AnyKernel/META-INF/com/google/android/update-binary
--- a/AnyKernel/META-INF/com/google/android/update-binary
+++ b/AnyKernel/META-INF/com/google/android/update-binary
@@ -1,10 +1,16 @@
 #!/sbin/sh
-# AnyKernel2 Backend (DO NOT CHANGE)
+# AnyKernel3 Backend (DO NOT CHANGE)
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
 ZIPFILE="$3";
-DIR=`dirname "$ZIPFILE"`;
+
+ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false;
+$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
+
+$BOOTMODE && DIR=/sdcard || DIR=$(dirname "$ZIPFILE");
+
+test "$home" || home=/tmp/anykernel;
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -24,27 +30,27 @@ int2ver() {
   fi;
 }
 cleanup() {
-  cd /tmp;
-  rm -rf /tmp/anykernel;
+  cd $(dirname $home);
+  rm -rf $home;
 }
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print " ";
-      ui_print "Creating debugging archive in zip directory...";
-      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
+      ui_print " " "- Creating debugging archive in $DIR...";
+      test -f /tmp/recovery.log && log=/tmp/recovery.log;
+      $bb tar -czf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $home $log;
     ;;
   esac;
 }
-is_mounted() { $bb mount | $bb grep " $1 "; }
+is_mounted() { $bb mount | $bb grep -q " $1 "; }
 unmount_all() {
-  (umount /system;
+  ($bb umount /system;
   if [ -d /system_root -a ! -f /system/build.prop ]; then
-    umount /system_root;
+    $bb umount /system_root;
   fi;
-  umount /system;
+  $bb umount /system;
   umount /vendor;
-  umount /data) 2>/dev/null;
+  $bb umount /data) 2>/dev/null;
 }
 abort() {
   ui_print "$*";
@@ -59,25 +65,43 @@ abort() {
 show_progress 1.34 4;
 ui_print " ";
 cleanup;
-mkdir -p /tmp/anykernel/bin;
-cd /tmp/anykernel;
+mkdir -p $home/bin;
+cd $home;
 unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls tools)" ]; then
-  abort "Unzip failed. Aborting...";
+if [ $? != 0 -o ! "$(ls tools)" ]; then
+  abort "- Unzip failed. Aborting...";
 fi;
-bb=/tmp/anykernel/tools/busybox;
+for arch32 in x86 arm; do
+  if [ -d $home/tools/$arch32 ]; then
+    bb=$home/tools/$arch32/busybox;
+    chmod 755 $bb;
+    $bb >/dev/null 2>&1;
+    if [ $? == 0 ]; then
+      $bb mv -f $home/tools/$arch32/* $home/tools;
+      break;
+    fi;
+  fi;
+done;
+bb=$home/tools/busybox;
 chmod 755 $bb;
 $bb chmod -R 755 tools bin;
+$bb --install -s bin;
+if [ $? != 0 -o -z "$(ls bin)" ]; then
+  abort "- Busybox setup failed. Aborting...";
+fi;
 
 if [ -f banner ]; then
   while IFS='' read -r line || $bb [[ -n "$line" ]]; do
     ui_print "$line";
   done < banner;
-  ui_print " ";
-  ui_print " ";
+  ui_print " " " ";
 fi;
 
-ui_print "$(file_getprop anykernel.sh kernel.string)";
+ui_print "****************************************";
+ui_print "* $(file_getprop anykernel.sh kernel.string)";
+ui_print "* For Xiaomi Redmi 4A ";
+ui_print "* Me Muhammad Fadly as ";
+ui_print "****************************************";
 if [ -f version ]; then
   ui_print " ";
   while IFS='' read -r line || $bb [[ -n "$line" ]]; do
@@ -85,17 +109,18 @@ if [ -f version ]; then
   done < version;
   ui_print " ";
 fi;
-ui_print " ";
-
+ui_print "- Checking ChipsImage";
+ui_print "- Founded ChipsImage ";
+ui_print "- Chips Codename: Fries ";
 unmount_all;
-if [ ! "$(is_mounted /system)" ]; then
+if ! is_mounted /system; then
   $bb mount -o ro -t auto /system;
 fi;
 ($bb mount -o ro -t auto /vendor;
 $bb mount /data) 2>/dev/null;
 if [ -f /system/system/build.prop ]; then
-  umount /system;
-  (umount /system;
+  $bb umount /system;
+  ($bb umount /system;
   mkdir /system_root) 2>/dev/null;
   $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
   $bb mount -o bind /system_root/system /system;
@@ -118,66 +143,86 @@ elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.pro
 fi;
 
 if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Cuma Bentar kok :")";
-  device="$(getprop ro.product.device)";
-  product="$(getprop ro.build.product)";
+  ui_print "- Checking device";
+  device=$(getprop ro.product.device);
+  product=$(getprop ro.build.product);
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
+      ui_print "- Device Codename: $testname";
       match=1;
       break;
     fi;
   done;
-  ui_print " ";
   if [ ! "$match" ]; then
-    abort "Oops! This is wrong device :(";
+    abort "- Unsupported device. Aborting...";
   fi;
 fi;
 
-supported_ver="$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]')";
+supported_ver=$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]');
 if [ "$supported_ver" ]; then
-  ui_print "Checking Android version...";
-  android_ver="$(file_getprop /system/build.prop ro.build.version.release)";
-  if [ "$(echo $supported_ver | $bb grep -)" ]; then
-    lo_ver=$(echo $supported_ver | $bb cut -d- -f1);
-    hi_ver=$(echo $supported_ver | $bb cut -d- -f2);
-    if [ "$(echo -e "$(int2ver $hi_ver)\n$(int2ver $lo_ver)\n$(int2ver $android_ver)" | $bb sort -g | $bb grep -n "$(int2ver $android_ver)" | $bb grep '^2:')" ]; then
+  ui_print "- Checking Android Version";
+  android_ver=$(file_getprop /system/build.prop ro.build.version.release);
+  parsed_ver=$(int2ver $android_ver);
+  if echo $supported_ver | $bb grep -q '-'; then
+    lo_ver=$(int2ver "$(echo $supported_ver | $bb cut -d- -f1)");
+    hi_ver=$(int2ver "$(echo $supported_ver | $bb cut -d- -f2)");
+    if echo -e "$hi_ver\n$lo_ver\n$parsed_ver" | $bb sort -g | $bb grep -n "$parsed_ver" | $bb grep -q '^2:'; then
       supported=1;
     fi;
   else
     for ver in $(echo $supported_ver | $bb sed 's;,; ;g'); do
-      if [ "$(int2ver $ver)" == "$(int2ver $android_ver)" ]; then
+      if [ "$(int2ver $ver)" == "$parsed_ver" ]; then
         supported=1;
         break;
       fi;
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver";
-    ui_print " ";
+    ui_print "- Android Version: $android_ver";
   else
-    ui_print " ";
-    abort "Unsupported Android version. Aborting...";
+    abort "- Unsupported Android version. Aborting...";
   fi;
 fi;
 
-ui_print "Pure kernel ini.Jangan lupa sholat,dzikir,ibadah jgn kebablasan main kernel%rom terus :")";
-for i in $($bb --list); do
-  $bb ln -s $bb bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
+supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $bb grep -oE '[0-9]{4}-[0-9]{2}|-');
+if [ "$supported_lvl" ]; then
+  ui_print "- Checking Android security patch level";
+  android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
+  parsed_lvl=$(echo $android_lvl | $bb grep -oE '[0-9]{4}-[0-9]{2}');
+  if echo $supported_lvl | $bb grep -q '^\-'; then
+    lo_lvl=0000-00;
+    hi_lvl=$(echo $supported_lvl | $bb awk '{ print $2 }');
+  elif echo $supported_lvl | $bb grep -q ' - '; then
+    lo_lvl=$(echo $supported_lvl | $bb awk '{ print $1 }');
+    hi_lvl=$(echo $supported_lvl | $bb awk '{ print $3 }');
+  elif echo $supported_lvl | $bb grep -q '\-$'; then
+    lo_lvl=$(echo $supported_lvl | $bb awk '{ print $1 }');
+    hi_lvl=9999-99;
+  fi;
+  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $bb sort -g | $bb grep -n "$parsed_lvl" | $bb grep -q '^2:'; then
+    ui_print "- Android security patch: $android_lvl";
+  else
+    abort "- Unsupported Android security patch level. Aborting...";
+  fi;
 fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash anykernel.sh $2;
+
+ui_print "- Backuping Boot.img";
+sleep 1
+ui_print "- Unpacking Boot.img";
+sleep 1
+ui_print "- Patching Boot.img";
+core=$($bb grep -oE 'ak.*core.sh' anykernel.sh);
+test -f tools/$core || $bb ln -s $home/tools/ak*-core.sh $home/tools/$core;
+PATH="$home/bin:$PATH" home=$home $bb ash anykernel.sh $2;
 if [ $? != 0 ]; then
   abort;
 fi;
 
 if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
-  ui_print " ";
-  ui_print "Pushing modules...";
+  ui_print "- Pushing modules";
   $bb mount -o rw,remount -t auto /system;
   $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
-  cd /tmp/anykernel/modules;
+  cd $home/modules;
   for module in $(find . -name '*.ko'); do
     modtarget=$(echo $module | $bb cut -c2-);
     if [ ! -e $modtarget ]; then
@@ -186,7 +231,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
         *) modcon=system;;
       esac;
     fi;
-    if [ "$(is_mounted $modtarget)" ]; then
+    if is_mounted $modtarget; then
       $bb mount -o rw,remount -t auto $modtarget;
     fi;
     mkdir -p $(dirname $modtarget);
@@ -196,11 +241,11 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
     if [ "$modcon" ]; then
       chcon "u:object_r:${modcon}_file:s0" $modtarget;
     fi;
-    if [ "$(is_mounted $modtarget)" ]; then
+    if is_mounted $modtarget; then
       $bb mount -o ro,remount -t auto $modtarget;
     fi;
   done;
-  cd /tmp/anykernel;
+  cd $home;
   $bb mount -o ro,remount -t auto /system;
   $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
@@ -214,10 +259,15 @@ fi;
 test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
 test "$savedpre" && export LD_PRELOAD="$savedpre";
 
+ui_print "- Repacking Boot.img";
+sleep 1
+ui_print "- Flashing Boot.img";
+sleep 2
+ui_print "- Unmount partitions";
+sleep 1
+
 unmount_all;
 
-ui_print " ";
-ui_print " ";
-ui_print "OkGanReboot!";
-ui_print " ";
-ui_print " ";
+ui_print "****************************************";
+ui_print "* Don't Forgot, god always watching!!!";
+ui_print "****************************************";
